-- Add KYC fields to vendor table
ALTER TABLE vendor ADD COLUMN IF NOT EXISTS phone VARCHAR(20);
ALTER TABLE vendor ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE vendor ADD COLUMN IF NOT EXISTS pan_number VARCHAR(20);
ALTER TABLE vendor ADD COLUMN IF NOT EXISTS gst_number VARCHAR(20);
ALTER TABLE vendor ADD COLUMN IF NOT EXISTS kyc_status VARCHAR(20) NOT NULL DEFAULT 'PENDING';
ALTER TABLE vendor ADD COLUMN IF NOT EXISTS kyc_rejection_reason TEXT;
ALTER TABLE vendor ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE vendor ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Vendor approval queue
CREATE TABLE IF NOT EXISTS vendor_approval_queue (
    id BIGSERIAL PRIMARY KEY,
    vendor_id BIGINT UNIQUE REFERENCES vendor(id) ON DELETE CASCADE,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP,
    reviewed_by BIGINT REFERENCES users(id),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    notes TEXT
);
